Botcopy/docs

- docs/index.html
> botcopy script

- docs/basics/branding.md
- docs/basics/connect.md
fix copy not showing due to markdown. add backticks
> fix code backticks

- docs/_coverpage.md
- docs/_sidebar.md
- docs/index.html
Add last updated
add sidebar footer for external links
update coverpage copy
> update cover page + footer + last updated

- docs/index.html
- docs/responses/botcopy-custom-payloads.md
add select as a field type to forms
> form select

- docs/_sidebar.md
- docs/basics/bot-prompts.md
- docs/basics/branding.md
- docs/wcag/focus-trap.md
- docs/window/events.md
- docs/window/methods.md
> focus trap

- docs/responses/videos.md
> video docs add vimeo

- docs/responses/botcopy-custom-payloads.md
- docs/responses/google-assistant.md
cleanup video references in ga + bc cards
> cleanup video references

- docs/advanced/handover.md
Update copy for Setup in Botcopy Portal for live chat endpoint
> cleanup formatting of setup

- docs/advanced/handover.md
> fix formatting

- docs/window/methods.md
> wrong button copy

- docs/responses/botcopy-custom-payloads.md
add multiline and row attributes to form docs
> add multiline and rows to form docs

- docs/window/methods.md
show showLanguages(boolean) method
> add showLanguages method

- docs/responses/botcopy-custom-payloads.md
show reserved characters and how to replace them
> add note on regex reserved json characters

- docs/window/events.md
- docs/window/methods.md
add setWindowStyle method
add bc-window-style event
> setWindowStyle method and event

- docs/basics/branding.md
add contained chat window style + other styles to docs
> update chat window style docs

- docs/basics/branding.md
- docs/wcag/focus-trap.md
add copy around contained styles and accessibility
> Contained style

- docs/basics/connect.md
add more instructions and clarity to tts docs
> cleanup tts docs

- docs/window/events.md
- docs/window/methods.md
docs for sound method and bc-sound-played event
> sound method

- docs/responses/botcopy-custom-payloads.md
- docs/window/events.md
> Bc initialized

- docs/livechat/handover.md
- docs/window/events.md
- docs/window/methods.md
Cleanup open endpoints docs
Rename org access token to API key
move body api key to header Botcopy -> Client
move body api key to header Client -> Botcopy
> rename acces tokens open endpoint docs

- docs/basics/connect.md
- docs/window/events.md
add more context to bc-initialized
add domain allowlist docs
> Bc initialized update

- docs/livechat/handover.md
Updated livechat docs with updated notion docs
> update live chat docs from notion

- docs/responses/botcopy-custom-payloads.md
Update response docs
https://www.loom.com/share/888a7ba39a14498ebe2247ecc88ceedd?sid=5f3e6758-45e9-4517-bcf3-2cb78f079de0
> Response design

- docs/window/methods.md
include a display: true boolean option.
> add display behavior

- docs/responses/botcopy-custom-payloads.md
Before:
https://docs.botcopy.com/#/responses/botcopy-custom-payloads?id=suggestions
After:
http://localhost:3000/#/responses/botcopy-custom-payloads?id=suggestions
> Add documentation for ariaLabel with suggestion chips

- docs/responses/botcopy-custom-payloads.md
Fixes: https://app.asana.com/1/322681378271782/project/1210547261744413/task/1209890583670775
> Add parameters on form params

- docs/responses/botcopy-custom-payloads.md
To be opened after geolocation is deployed to production
> Geolocation
